### ISSUE TITLE
how to get data

### ISSUE THREAD

**Issue by wxhhxn** [teejusb/ml#1]
Hello, I would like to inquire why the dataset I downloaded is a collection of .arrow files, and how this can be resolved.

**Comment by wxhhxn** [comment]
Hello, I would like to inquire why the dataset I downloaded is a collection of .arrow files, and how this can be resolved.I apologize, I was unaware that “ask” carries an interrogative tone.

**Comment by teejusb** [comment]
What the. This is just an educational repo for myself and doesn't have any datesets included so I don't know the answer.
